CREATE TABLE USUARIOS(
ID SERIAL,
NOMBRES CHARACTER VARYING (25) NOT NULL,
APELLIDOS CHARACTER VARYING (25) NOT NULL,
CEDULAS CHARACTER VARYING (25) NOT NULL,
ZONA CHARACTER VARYING (25) NOT NULL,
CELULAR CHARACTER VARYING(25) NOT NULL,
ACTIVO BOOLEAN NOT NULL
);